// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	fmt "fmt"

	mock "github.com/stretchr/testify/mock"
)

// OrderNotFoundError is an autogenerated mock type for the OrderNotFoundError type
type OrderNotFoundError struct {
	mock.Mock
}

// Cause provides a mock function with given fields:
func (_m *OrderNotFoundError) Cause() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Cause")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Error provides a mock function with given fields:
func (_m *OrderNotFoundError) Error() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Format provides a mock function with given fields: f, verb
func (_m *OrderNotFoundError) Format(f fmt.State, verb rune) {
	_m.Called(f, verb)
}

// IsCustomError provides a mock function with given fields:
func (_m *OrderNotFoundError) IsCustomError() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsCustomError")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// IsNotFoundError provides a mock function with given fields:
func (_m *OrderNotFoundError) IsNotFoundError() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsNotFoundError")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Message provides a mock function with given fields:
func (_m *OrderNotFoundError) Message() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Message")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Status provides a mock function with given fields:
func (_m *OrderNotFoundError) Status() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Unwrap provides a mock function with given fields:
func (_m *OrderNotFoundError) Unwrap() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Unwrap")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOrderNotFoundError creates a new instance of OrderNotFoundError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderNotFoundError(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderNotFoundError {
	mock := &OrderNotFoundError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
